replit/replit.github.io

sidebar.json

didnt notice that it was missing in #3

add security to sidebar

---

repls/web-hosting.md
sidebar.json

Placeholder for if/when @turbio writes the docs :)

Placeholder for custom domains

---

misc/quick-start.md
sidebar.json

Re: https://repl.it/bugs/p/template-error-in-quick-start-document

fix dashboard link in quickstart

---

classrooms/embed.md

Updated LTI Deprecation

---

classrooms/exports.md
sidebar.json

add doc for exports

---

repls/secret-keys.md

env files can be seen by others in multiplayer, we should probably give a warning for this.

add warning for multiplayer

---

classrooms/autograding.md
classrooms/management.md
classrooms/markdown.md
classrooms/pricing-faq.md
classrooms/webhooks.md
misc/copyright.md
misc/public-schools.md
repls/dashboard.md
repls/files.md
repls/http-servers.md
repls/web-hosting.md

Ensures that each article has an intro paragraph for docs page metadata.

ensure intros

---

classrooms/assignment-submission.md
classrooms/autograding.md
classrooms/community.md
classrooms/embed.md
classrooms/exports.md
repls/embed.md
repls/secret-keys.md
repls/web-hosting.md

Shortens intros to <=250 chars

shorten intros

---

classrooms/webhooks.md

Just added a link to a canny feedback post.

updated link to feedback post

---

repls/dashboard.md

we can revert is we decide to re-enable

remove mention of tags

---

repls/dot-replit.md

Fix typo in dot-replit.md

---

repls/dot-replit.md

A simple "This will... make" fix.
This will ... create ... and make ...
^^ each verb has to be the same with an "and"

Grammar fix (parallel structure)

---

misc/basic.md

sync repl.it basic docs with basic github docs

update basic documentation

---

misc/free-features.md
misc/licensing.md
repls/dashboard.md
repls/dot-replit.md
repls/embed.md
repls/files.md
repls/http-servers.md
repls/multiplayer-anon.md
repls/packages.md
repls/web-hosting.md

Corrected grammar, reworded things for clarity, and fixed a few typos.

grammar and typo fixes

---

repls/http-servers.md

The current demo repl is returning server errors, so this PR updates the embed to a new, tested repl.

update flask example

---

repls/ audio.md
repls/audio.md
sidebar.json

Just like the title says. Added some docs for audio so users can create their own libs or just understand how it works.

Added some docs for audio.

---

repls/web-hosting.md

We should tell people about this!

Docs for username.repl.co hosting

---

misc/clui.md

Some more commands were added.

Add more CLUI command docs

---

misc/achievements.md

Fix styling achievements

---

repls/audio.md

Updated docs for audio

---

misc/database.md

We don't yet support attaching the same database to multiple repls, but there's a workaround/hack that we might as well document!

add shared database example

---

Teams/CentralizedAutograder.md
Teams/CentralizedAutograderQuickstart.md
Teams/SimpleAutograding.md

fix up the links between the different autograding articles and add the quickstart guide.

fix links add quickstart

---

Teams/Intro.md

update intro to teams to fix signup process and add higher quality screenshots with better cropping and annotations.

update intro, better screenshots

---

Teams/SimpleAutograding-java.md
Teams/Testing.md

add simple autograding java translation

Simple autograding java

---

Teams/CentralizedAutograder-java.md

add centralized autograder - java version.

add centralized autograder

---

Teams/Intro.md

fix beta wording

---

Teams/CentralizedAutograder-java.md
Teams/CentralizedAutograder.md
Teams/SimpleAutograding-java.md
Teams/SimpleAutograding.md

* mention annotation in autograder aritcles
* also change 'fork' to "start project" where relevant

Add links to annotations autograders

---

sidebar.json
tutorials/00-overview.md

-Add steganography to overview page
-Add input/output tests to sidebar

Add steg to overview page

---

repls/UnitTesting.md
repls/always-on.md
repls/audio.md
repls/dashboard.md
repls/dot-replit.md
repls/editor.md
repls/embed.md
repls/http-servers.md
repls/multiplayer-anon.md
repls/repl-from-repo.md
sidebar.json

Reverts replit/replit.github.io#158

Revert "getting started edits"

---

Teams/Annotations.md
Teams/EmbedProjects.md
Teams/HomeworkAssignments.md
Teams/IT_Toolkit.md
Teams/InputOutput.md
Teams/Intro.md
Teams/Invitations.md
Teams/Notes.md
Teams/Projects.md
Teams/Roles.md
Teams/privacyFAQs.md
Teams/projectCopying.md
sidebar.json
views/index.ejs

Reverts replit/replit.github.io#165

Revert "Teams4Ed Edit complete"

---

tutorials/20-online-store-checkout-process.md

Fix typo of `index.js` when it should be `index.html`

---

tutorials/23-build-asteroids-with-kaboom.md

Reverts replit/replit.github.io#313

Revert "Add a note to kaboom asteroids tutorial"
